name: Python Script

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Test macvendor output
      run: |
        output=$(python macvendor --no-update B0:EA:BC:00:00:00)
        if [ "$output" != "B0:EA:BC:00:00:00, ASKEY COMPUTER CORP" ]; then
          echo "Unexpected output: $output"
          exit 1
        fi